feat: git configuration
- show graph in `git lol`
- add git_config to make working with git easier
- cleanup prompt to show both git branch info and python venv

diff --git a/bash/.config/bash/prompt b/bash/.config/bash/prompt
--- a/bash/.config/bash/prompt
+++ b/bash/.config/bash/prompt
@@ -1,98 +1,122 @@
 #!/usr/bin/bash
 
-# Original:  https://github.com/riobard/bash-powerline
+# Original:  https://gist.github.com/miki725/9783474
 # Changed by Tim
 
-function timer_start {
-    timer=${timer:-$SECONDS}
-}
+#!/bin/bash
+#
+# DESCRIPTION:
+#
+#   Set the bash prompt according to:
+#    * the active virtualenv
+#    * the branch of the current git/mercurial repository
+#    * the return value of the previous command
+#    * the fact you just came from Windows and are used to having newlines in
+#      your prompts.
+#
+# USAGE:
+#
+#   1. Save this file as ~/.bash_prompt
+#   2. Add the following line to the end of your ~/.bashrc or ~/.bash_profile:
+#        . ~/.bash_prompt
+#
+# LINEAGE:
+#
+#   Based on work by woods
+#
+#   https://gist.github.com/31967
 
-function timer_stop {
-    timer_show=$(($SECONDS - $timer))
-    unset timer
-}
+# The various escape codes that we can use to color our prompt.
+RED="\[\033[0;31m\]"
+YELLOW="\[\033[1;33m\]"
+GREEN="\[\033[0;32m\]"
+BLUE="\[\033[1;34m\]"
+PURPLE="\[\033[0;35m\]"
+LIGHT_RED="\[\033[1;31m\]"
+LIGHT_GREEN="\[\033[1;32m\]"
+WHITE="\[\033[1;37m\]"
+LIGHT_GRAY="\[\033[0;37m\]"
+COLOR_NONE="\[\e[0m\]"
 
-trap 'timer_start' DEBUG
+# Symbols
+SYMBOL_GIT_BRANCH=${SYMBOL_GIT_BRANCH:-⑂}
+SYMBOL_GIT_MODIFIED=${SYMBOL_GIT_MODIFIED:-*}
+SYMBOL_GIT_PUSH=${SYMBOL_GIT_PUSH:-↑}
+SYMBOL_GIT_PULL=${SYMBOL_GIT_PULL:-↓}
 
-__prompt() {
-    # Colors
-    COLOR_RESET='\[\033[m\]'
-    COLOR_CWD=${COLOR_CWD:-'\[\033[0;34m\]'} # blue
-    COLOR_GIT=${COLOR_GIT:-'\[\033[0;33m\]'} # brown
-    COLOR_USER=${COLOR_USER:-'\[\033[0;36m\]'} # cyan
-    COLOR_HOST=${COLOR_HOST:-'\[\033[0;36m\]'} # cyan
-    COLOR_TIMER=${COLOR_TIMER:-'\[\033[0;32m\]'} # green
-    COLOR_SUCCESS=${COLOR_SUCCESS:-'\[\033[0;32m\]'} # green
-    COLOR_FAILURE=${COLOR_FAILURE:-'\[\033[0;31m\]'} # red
+# determine git branch name
+function parse_git_info(){
+    # get current branch name
+    local ref=$(git symbolic-ref --short HEAD 2>/dev/null)
+    [ "$ref" = "" ] && ref=$(git rev-parse --short HEAD 2>/dev/null)
+    [ "${ref}" = "" ] && return  # not a git repo
 
-    # Symbols
-    SYMBOL_GIT_BRANCH=${SYMBOL_GIT_BRANCH:-⑂}
-    SYMBOL_GIT_MODIFIED=${SYMBOL_GIT_MODIFIED:-*}
-    SYMBOL_GIT_PUSH=${SYMBOL_GIT_PUSH:-↑}
-    SYMBOL_GIT_PULL=${SYMBOL_GIT_PULL:-↓}
+    # prepend branch symbol
+    ref=$SYMBOL_GIT_BRANCH$ref
 
-    #PS_SYMBOL='🗽>'
-    PS_SYMBOL='\n>'
+    local marks
 
-    __git_info() { 
-        # get current branch name
-        local ref=$(git symbolic-ref --short HEAD 2>/dev/null)
-        [ "$ref" = "" ] && ref=$(git rev-parse --short HEAD 2>/dev/null)
-        [ "${ref}" = "" ] && return  # not a git repo
-
-        # prepend branch symbol
-        ref=$SYMBOL_GIT_BRANCH$ref
-
-        local marks
-
-        # scan first two lines of output from `git status`
-        while IFS= read -r line; do
-            if [[ $line =~ ^## ]]; then # header line
-                [[ $line =~ ahead\ ([0-9]+) ]] && marks+=" $SYMBOL_GIT_PUSH${BASH_REMATCH[1]}"
-                [[ $line =~ behind\ ([0-9]+) ]] && marks+=" $SYMBOL_GIT_PULL${BASH_REMATCH[1]}"
-            else # branch is modified if output contains more lines after the header line
-                marks="$SYMBOL_GIT_MODIFIED$marks"
-                break
-            fi
-        done < <(git status --porcelain --branch 2>/dev/null)  # note the space between the two <
-
-        # print the git branch segment without a trailing newline
-        printf "$ref$marks"
-        unset ref
-    }
-
-    ps1() {
-        timer_stop
-
-        # Check the exit code of the previous command and display different
-        # colors in the prompt accordingly. 
-        if [ $? -eq 0 ]; then
-            local symbol="$COLOR_SUCCESS $PS_SYMBOL $COLOR_RESET"
-        else
-            local symbol="$COLOR_FAILURE $PS_SYMBOL $COLOR_RESET"
+    # scan first two lines of output from `git status`
+    while IFS= read -r line; do
+        if [[ $line =~ ^## ]]; then # header line
+            [[ $line =~ ahead\ ([0-9]+) ]] && marks+=" $SYMBOL_GIT_PUSH${BASH_REMATCH[1]}"
+            [[ $line =~ behind\ ([0-9]+) ]] && marks+=" $SYMBOL_GIT_PULL${BASH_REMATCH[1]}"
+        else # branch is modified if output contains more lines after the header line
+            marks="$SYMBOL_GIT_MODIFIED$marks"
+            break
         fi
+    done < <(git status --porcelain --branch 2>/dev/null)  # note the space between the two <
 
-        local cwd="$COLOR_CWD\w$COLOR_RESET"
-        local userhost="$COLOR_USER[\u$COLOR_HOST@\h]$COLOR_RESET"
-        local timer="$COLOR_TIMER[last: ${timer_show}s]$COLOR_RESET"
-        # Bash by default expands the content of PS1 unless promptvars is disabled.
-        # We must use another layer of reference to prevent expanding any user
-        # provided strings, which would cause security issues.
-        # POC: https://github.com/njhartwell/pw3nage
-        # Related fix in git-bash: https://github.com/git/git/blob/9d77b0405ce6b471cb5ce3a904368fc25e55643d/contrib/completion/git-prompt.sh#L324
-        if shopt -q promptvars; then
-            __prompt_git_info="$(__git_info)"
-            local git="$COLOR_GIT[\${__prompt_git_info}]$COLOR_RESET"
-        else
-            # promptvars is disabled. Avoid creating unnecessary env var.
-            local git="$COLOR_GIT[$(__git_info)]$COLOR_RESET"
-        fi
-
-        PS1="$git $cwd$symbol"
-    }
-
-    PROMPT_COMMAND="ps1${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
+    # print the git branch segment without a trailing newline
+    printf " ($ref$marks)"
+    unset ref
 }
 
-__prompt
-unset __prompt
+# Determine the branch/state information for this git repository.
+function set_git_branch() {
+    # Get the name of the branch.
+    branch=$(parse_git_info)
+
+    # Set the final branch string.
+    BRANCH="${PURPLE}${branch}${COLOR_NONE} "
+}
+
+# Return the prompt symbol to use, colorized based on the return value of the
+# previous command.
+function set_prompt_symbol () {
+    if test $1 -eq 0 ; then
+    PROMPT_SYMBOL="\$"
+    else
+    PROMPT_SYMBOL="${LIGHT_RED}\$${COLOR_NONE}"
+    fi
+}
+
+# Determine active Python virtualenv details.
+function set_virtualenv () {
+    if test -z "$VIRTUAL_ENV" ; then
+    PYTHON_VIRTUALENV=""
+    else
+    PYTHON_VIRTUALENV="${BLUE}[`basename \"$VIRTUAL_ENV\"`]${COLOR_NONE} "
+    fi
+}
+
+# Set the full bash prompt.
+function set_bash_prompt () {
+    # Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
+    # return value of the last command.
+    set_prompt_symbol $?
+
+    # Set the PYTHON_VIRTUALENV variable.
+    set_virtualenv
+
+    # Set the BRANCH variable.
+    set_git_branch
+
+    # Set the bash prompt variable.
+    PS1="
+${PYTHON_VIRTUALENV}${GREEN}\u@\h${COLOR_NONE}:${YELLOW}\w${COLOR_NONE}${BRANCH}
+${PROMPT_SYMBOL} "
+}
+
+# Tell bash to execute this function just before displaying its prompt.
+PROMPT_COMMAND=set_bash_prompt
